[main]
enable_esc_key = true
[modules]
left = [ [ "Workspaces" ], "MediaPlayer"]
center = [ "WindowTitle" ]
right = [ "Tray", "SystemInfo", [   "Clock", "Privacy", "Settings" ] ]
[workspaces]
visibility_mode = "All"
enable_workspace_filling = true
max_workspaces = 10
[settings]
shutdown_cmd = "shutdown now"
suspend_cmd = "systemctl suspend"
reboot_cmd = "systemctl reboot"
logout_cmd = "loginctl kill-user $(whoami)"
[appearance]
scale_factor = 1.1
style = "Solid"
opacity = 0.9
font_name = "Roboto Mono"
font_size = 25

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#cdd6f4"

workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"
